#!/usr/bin/env python3
"""
Konoha Dogfood Mission Suite.

Runs a bounded suite of Konoha's own safe local-first workflows as dogfood.
This tool delegates only to allowlisted internal tools and writes one report
under sandbox/reports.

It does not execute mission actions, call real adapters, perform Git writes,
access private context, or use network access.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


APPROVAL_TOKEN = "INVOKE_ADAPTER_GATE"
RUN_ID_RE = re.compile(r"^[A-Za-z0-9._-]+$")


class DogfoodError(ValueError):
    """Raised when dogfood inputs violate local safety constraints."""


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def validate_run_id(run_id: str) -> str:
    if not run_id or not RUN_ID_RE.fullmatch(run_id):
        raise DogfoodError(
            "run_id must be alphanumeric plus '.', '_' or '-' and may not contain path separators"
        )
    if run_id in {".", ".."} or ".." in run_id:
        raise DogfoodError("run_id may not be '.', '..', or contain '..'")
    return run_id


def resolve_under(root: Path, candidate: str) -> Path:
    root_resolved = root.resolve()
    resolved = (root_resolved / candidate).resolve()
    if resolved != root_resolved and root_resolved not in resolved.parents:
        raise DogfoodError(f"path escapes root: {candidate}")
    return resolved


def command_to_text(command: list[str]) -> str:
    return " ".join(command)


def run_command(command: list[str], repo_root: Path, timeout_seconds: int) -> dict[str, object]:
    completed = subprocess.run(
        command,
        cwd=str(repo_root),
        text=True,
        capture_output=True,
        timeout=timeout_seconds,
        shell=False,
    )
    return {
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def build_steps(repo_root: Path, sandbox_root: Path, run_id: str, config_path: Path) -> list[dict[str, object]]:
    py = sys.executable
    repo = str(repo_root)
    sandbox = str(sandbox_root)
    config = str(config_path)

    mission_run_id = f"{run_id}-mission"
    artifact_run_id = f"{run_id}-artifact"
    adapter_run_id = f"{run_id}-adapter"

    return [
        {
            "name": "project_config_validation",
            "purpose": "Validate public project config and policy defaults.",
            "command": [
                py,
                str(repo_root / "tools" / "config_validator" / "validate_konoha_config.py"),
                config,
            ],
        },
        {
            "name": "end_to_end_dry_run_mission_workflow",
            "purpose": "Run mission-level dry-run workflow using existing gates.",
            "command": [
                py,
                str(repo_root / "tools" / "mission_workflow" / "run_dry_run_mission.py"),
                "--title",
                "Dogfood mission workflow",
                "--scope",
                "Dogfood Konoha's end-to-end dry-run mission workflow.",
                "--run-id",
                mission_run_id,
                "--repo-root",
                repo,
                "--sandbox-root",
                sandbox,
                "--config",
                config,
                "--force",
            ],
        },
        {
            "name": "proposed_artifact_workflow_preview",
            "purpose": "Create a proposed artifact inside sandbox and preview apply only.",
            "command": [
                py,
                str(repo_root / "tools" / "artifact_workflow" / "run_proposed_artifact_workflow.py"),
                "--title",
                "Dogfood proposed artifact workflow",
                "--scope",
                "Dogfood proposed artifact creation and apply preview.",
                "--run-id",
                artifact_run_id,
                "--repo-root",
                repo,
                "--sandbox-root",
                sandbox,
                "--artifact-path",
                "docs/dogfood_note.md",
                "--content",
                "# Dogfood proposed artifact\n\nGenerated by the Konoha dogfood mission suite.",
                "--artifact-kind",
                "markdown",
                "--intended-repo-path",
                f"sandbox/tmp/{artifact_run_id}/dogfood_note.md",
                "--force",
            ],
        },
        {
            "name": "adapter_gate_run_preparation",
            "purpose": "Prepare a sandbox run before adapter gate dogfood.",
            "command": [
                py,
                str(repo_root / "tools" / "runtime_runner" / "run_dry_run_runtime.py"),
                "--title",
                "Dogfood adapter gate run",
                "--scope",
                "Prepare a dry-run sandbox run for adapter gate dogfood.",
                "--run-id",
                adapter_run_id,
                "--sandbox-root",
                sandbox,
                "--force",
            ],
        },
        {
            "name": "adapter_invocation_gate_preview",
            "purpose": "Preview adapter invocation while all real adapter execution remains blocked.",
            "command": [
                py,
                str(repo_root / "tools" / "adapter_gate" / "invoke_adapter_gate.py"),
                "--sandbox-root",
                sandbox,
                "--run-id",
                adapter_run_id,
                "--adapter",
                "mock",
                "--task",
                "Draft a dogfood checklist.",
                "--mode",
                "checklist",
            ],
        },
        {
            "name": "adapter_invocation_gate_mock_confirmed",
            "purpose": "Invoke only deterministic mock adapter with explicit gate approval.",
            "command": [
                py,
                str(repo_root / "tools" / "adapter_gate" / "invoke_adapter_gate.py"),
                "--sandbox-root",
                sandbox,
                "--run-id",
                adapter_run_id,
                "--adapter",
                "mock",
                "--task",
                "Draft a dogfood checklist.",
                "--mode",
                "checklist",
                "--confirm-invocation",
                "--approval-token",
                APPROVAL_TOKEN,
                "--enable-mock-adapter",
                "--force",
            ],
        },
        {
            "name": "repo_inspection",
            "purpose": "Inspect public repository coherence in read-only mode.",
            "command": [
                py,
                str(repo_root / "tools" / "repo_inspector" / "inspect_public_repo.py"),
                "--repo-root",
                repo,
            ],
        },
        {
            "name": "git_readiness_read_only",
            "purpose": "Inspect Git readiness without write operations.",
            "command": [
                py,
                str(repo_root / "tools" / "git_readiness" / "inspect_git_readiness.py"),
                "--repo-root",
                repo,
                "--allow-dirty",
            ],
        },
    ]


def write_report(report_path: Path, report: dict[str, object]) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def make_report(
    run_id: str,
    repo_root: Path,
    sandbox_root: Path,
    report_path: Path,
    status: str,
    steps: list[dict[str, object]],
    blockers: list[str],
) -> dict[str, object]:
    passed = [step for step in steps if step.get("status") == "passed"]
    failed = [step for step in steps if step.get("status") == "failed"]

    return {
        "schema_version": "1.0.0",
        "suite": "konoha_dogfood_mission_suite",
        "run_id": run_id,
        "status": status,
        "created_at": utc_now(),
        "repo_root": str(repo_root),
        "sandbox_root": str(sandbox_root),
        "report_path": str(report_path),
        "summary": {
            "total_steps": len(steps),
            "passed_steps": len(passed),
            "failed_steps": len(failed),
            "blockers": blockers,
        },
        "boundaries": {
            "execution": "blocked",
            "filesystem_mutation": "sandbox reports and delegated sandbox outputs only",
            "repository_apply": "blocked",
            "git_operations": "read-only or blocked",
            "git_write_operations": "blocked",
            "private_context_access": "blocked",
            "adapter_execution": "mock only through adapter gate",
            "real_adapter_execution": "blocked",
            "network_access": "blocked",
        },
        "steps": steps,
        "human_review_required": True,
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run Konoha dogfood mission suite using only safe local-first gates."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root.")
    parser.add_argument("--sandbox-root", default="./sandbox", help="Sandbox root.")
    parser.add_argument("--run-id", required=True, help="Dogfood run id.")
    parser.add_argument(
        "--config",
        default="./konoha.config.example.json",
        help="Konoha project config path.",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=120,
        help="Timeout per delegated step.",
    )
    parser.add_argument("--json", action="store_true", help="Print JSON report.")
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])

    steps: list[dict[str, object]] = []
    blockers: list[str] = []

    try:
        run_id = validate_run_id(args.run_id)
        repo_root = Path(args.repo_root).resolve()
        sandbox_root = Path(args.sandbox_root).resolve()
        config_path = Path(args.config).resolve()

        if not repo_root.exists():
            raise DogfoodError(f"repo_root does not exist: {repo_root}")
        if not config_path.exists():
            raise DogfoodError(f"config does not exist: {config_path}")

        reports_dir = resolve_under(sandbox_root, "reports")
        report_path = resolve_under(reports_dir, f"{run_id}_dogfood_mission_suite_report.json")

        planned_steps = build_steps(repo_root, sandbox_root, run_id, config_path)
        for planned in planned_steps:
            result = run_command(
                planned["command"],  # type: ignore[arg-type]
                repo_root=repo_root,
                timeout_seconds=args.timeout_seconds,
            )
            returncode = int(result["returncode"])
            step_status = "passed" if returncode == 0 else "failed"
            step = {
                "name": planned["name"],
                "purpose": planned["purpose"],
                "status": step_status,
                "returncode": returncode,
                "command": command_to_text(planned["command"]),  # type: ignore[arg-type]
                "stdout_tail": str(result.get("stdout", ""))[-2000:],
                "stderr_tail": str(result.get("stderr", ""))[-2000:],
            }
            steps.append(step)
            if step_status != "passed":
                blockers.append(f"{planned['name']} returned {returncode}")
                break

        status = "passed" if not blockers else "failed"
        report = make_report(run_id, repo_root, sandbox_root, report_path, status, steps, blockers)
        write_report(report_path, report)

    except Exception as exc:
        status = "failed"
        blockers.append(str(exc))
        run_id = getattr(args, "run_id", "unknown")
        repo_root = Path(getattr(args, "repo_root", ".")).resolve()
        sandbox_root = Path(getattr(args, "sandbox_root", "./sandbox")).resolve()
        report_path = sandbox_root / "reports" / f"{run_id}_dogfood_mission_suite_report.json"
        report = make_report(str(run_id), repo_root, sandbox_root, report_path, status, steps, blockers)
        try:
            write_report(report_path, report)
        except Exception:
            pass

    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    elif status == "passed":
        print("DOGFOOD MISSION SUITE PASSED")
        print(f"Run id: {report['run_id']}")
        print(f"Steps passed: {report['summary']['passed_steps']}/{report['summary']['total_steps']}")
        print("Execution: blocked")
        print("Filesystem mutation: sandbox reports and delegated sandbox outputs only")
        print("Repository apply: blocked")
        print("Git operations: read-only or blocked")
        print("Git write operations: blocked")
        print("Private context access: blocked")
        print("Adapter execution: mock only through adapter gate")
        print("Real adapter execution: blocked")
        print("Network access: blocked")
    else:
        print("DOGFOOD MISSION SUITE FAILED")
        print(f"Run id: {report['run_id']}")
        print("Execution: blocked")
        print("Repository apply: blocked")
        print("Git write operations: blocked")
        print("Private context access: blocked")
        print("Real adapter execution: blocked")
        print("Network access: blocked")
        for blocker in blockers:
            print(f"Blocker: {blocker}")

    return 0 if status == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
