"""Canonical command registry for the Konoha terminal entrypoint.

Registry metadata is descriptive evidence. It does not authorize the delegated
tool, provide approval tokens, enable network, or weaken delegated gates.
"""

from __future__ import annotations

from typing import Any, Dict, Tuple

CommandKey = Tuple[str, ...]

COMMAND_REGISTRY: Dict[CommandKey, Dict[str, Any]] = {
    ("welcome",): {
        "script": "tools/product_experience/run_product_experience.py",
        "fixed_args": ["welcome"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Show product readiness and one next action.",
    },
    ("quickstart",): {
        "script": "tools/product_experience/run_product_experience.py",
        "fixed_args": ["quickstart"],
        "mode": "workspace_write",
        "network": "blocked",
        "approval_token": "START_KONOHA_QUICKSTART",
        "status": "active",
        "description": "Initialize the finished local workspace experience.",
    },
    ("next",): {
        "script": "tools/product_experience/run_product_experience.py",
        "fixed_args": ["next"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Inspect evidence and show one next command.",
    },
    ("doctor",): {
        "script": "tools/product_runtime/konoha_product.py",
        "fixed_args": ["doctor"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Run product runtime diagnostics.",
    },
    ("init",): {
        "script": "tools/product_runtime/konoha_product.py",
        "fixed_args": ["init"],
        "mode": "workspace_write",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Initialize a local Konoha workspace.",
    },
    ("status",): {
        "script": "tools/hokage_shell/run_hokage_shell.py",
        "fixed_args": ["status"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Show terminal operator status.",
    },
    ("shell",): {
        "script": (
            "tools/hokage_orchestrator/"
            "run_conversational_hokage.py"
        ),
        "fixed_args": [],
        "mode": "interactive_supervised",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Open the conversational Hokage product shell.",
    },
    ("shell", "legacy"): {
        "script": "tools/hokage_shell/run_hokage_shell.py",
        "fixed_args": ["interactive"],
        "mode": "interactive_supervised",
        "network": "delegated_explicit_only",
        "approval_token": None,
        "status": "active",
        "description": "Open the legacy menu-driven Hokage shell.",
    },
    ("mission", "start"): {
        "script": "tools/beta_runtime/run_konoha_beta.py",
        "fixed_args": ["start"],
        "mode": "mission_write",
        "network": "blocked",
        "approval_token": "START_BETA_MISSION",
        "status": "active",
        "description": "Start a supervised mission.",
    },
    ("mission", "run"): {
        "script": "tools/mission_runtime/run_unified_mission.py",
        "fixed_args": ["run"],
        "mode": "mission_write",
        "network": "blocked",
        "approval_token": "START_UNIFIED_MISSION_RUNTIME",
        "status": "active",
        "description": "Prepare a unified mission runtime.",
    },
    ("mission", "plan"): {
        "script": "tools/beta_runtime/run_konoha_beta.py",
        "fixed_args": ["plan"],
        "mode": "mission_write",
        "network": "blocked",
        "approval_token": "PLAN_BETA_MISSION",
        "status": "active",
        "description": "Record a mission plan and proposals.",
    },
    ("mission", "review"): {
        "script": "tools/beta_runtime/run_konoha_beta.py",
        "fixed_args": ["review"],
        "mode": "human_evidence_write",
        "network": "blocked",
        "approval_token": "RECORD_BETA_REVIEW",
        "status": "active",
        "description": "Record a human review decision.",
    },
    ("mission", "teachback"): {
        "script": "tools/teachback/manage_teachback.py",
        "fixed_args": ["record"],
        "mode": "human_evidence_write",
        "network": "blocked",
        "approval_token": "RECORD_TEACHBACK_EVIDENCE",
        "status": "active",
        "description": "Record structured human Teachback evidence.",
    },
    ("mission", "teachback-status"): {
        "script": "tools/teachback/manage_teachback.py",
        "fixed_args": ["status"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Inspect structured Teachback evidence.",
    },
    ("mission", "teachback-prepare"): {
        "script": "tools/teachback/manage_teachback.py",
        "fixed_args": ["prepare"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Inspect mission Teachback requirements.",
    },
    ("mission", "close"): {
        "script": "tools/mission_closure/close_mission.py",
        "fixed_args": [],
        "mode": "mission_and_memory_write",
        "network": "blocked",
        "approval_token": "CLOSE_MISSION_WITH_TEACHBACK",
        "status": "active",
        "description": "Close after execution, review and Teachback.",
    },
    ("mission", "status"): {
        "script": "tools/beta_runtime/run_konoha_beta.py",
        "fixed_args": ["status"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Inspect mission status.",
    },
    ("mission", "resume"): {
        "script": "tools/hokage_shell/run_hokage_shell.py",
        "fixed_args": ["resume"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Build a read-only mission continuity report.",
    },
    ("package", "status"): {
        "script": "tools/package_installation/run_supervised_package_installation.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Preview supervised package installation.",
    },
    ("package", "install"): {
        "script": "tools/package_installation/run_supervised_package_installation.py",
        "fixed_args": ["--apply"],
        "mode": "bounded_package_write",
        "network": "blocked",
        "approval_token": "APPLY_SUPERVISED_PACKAGE_INSTALLATION",
        "status": "active",
        "description": "Apply a bounded package helper.",
    },
    ("release", "status"): {
        "script": "tools/release_workflow/run_supervised_release.py",
        "fixed_args": ["--status"],
        "mode": "read_only",
        "network": "optional_read_only",
        "approval_token": None,
        "status": "active",
        "description": "Inspect release recovery and closure state.",
    },
    ("release", "deliver"): {
        "script": "tools/release_delivery/run_supervised_package_release.py",
        "fixed_args": [],
        "mode": "package_test_git_release_write",
        "network": "explicit_only",
        "approval_token": "RUN_SUPERVISED_PACKAGE_RELEASE",
        "status": "active",
        "description": "Run the supervised package-to-release wrapper.",
    },
    ("install-status",): {
        "script": "tools/distribution/manage_konoha_distribution.py",
        "fixed_args": ["status"],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "active",
        "description": "Inspect the managed terminal installation.",
    },
    ("upgrade",): {
        "script": "tools/distribution/manage_konoha_distribution.py",
        "fixed_args": ["upgrade"],
        "mode": "managed_install_write",
        "network": "explicit_only",
        "approval_token": "UPGRADE_KONOHA_INSTALL",
        "status": "active",
        "description": "Upgrade a verified managed installation.",
    },
    ("uninstall",): {
        "script": "tools/distribution/manage_konoha_distribution.py",
        "fixed_args": ["uninstall"],
        "mode": "recoverable_install_remove",
        "network": "blocked",
        "approval_token": "UNINSTALL_KONOHA_CLI",
        "status": "active",
        "description": "Move a verified installation to recoverable trash.",
    },
}

LEGACY_COMMANDS: Dict[CommandKey, Dict[str, Any]] = {
    ("mission", "dry-run"): {
        "script": "tools/mission_workflow/run_dry_run_mission.py",
        "fixed_args": [],
        "mode": "sandbox_write",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "mission run",
        "description": "Legacy dry-run mission workflow.",
    },
    ("runtime", "dry-run"): {
        "script": "tools/runtime_runner/run_dry_run_runtime.py",
        "fixed_args": [],
        "mode": "sandbox_write",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "mission run",
        "description": "Legacy dry-run runtime.",
    },
    ("package", "validate"): {
        "script": "tools/runtime_validator/validate_runtime_package.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "package status",
        "description": "Legacy runtime package validator.",
    },
    ("package", "inspect"): {
        "script": "tools/runtime_inspector/inspect_runtime_package.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "package status",
        "description": "Legacy runtime package inspector.",
    },
    ("runs", "list"): {
        "script": "tools/runtime_registry/list_runtime_runs.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "mission status",
        "description": "Legacy runtime run registry.",
    },
    ("repo", "inspect"): {
        "script": "tools/repo_inspector/inspect_public_repo.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "shell",
        "description": "Legacy public repo inspector.",
    },
    ("git", "readiness"): {
        "script": "tools/git_readiness/inspect_git_readiness.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "release status",
        "description": "Legacy Git readiness inspector.",
    },
    ("git", "stage"): {
        "script": "tools/git_staging/stage_allowlisted_files.py",
        "fixed_args": [],
        "mode": "git_write",
        "network": "blocked",
        "approval_token": "delegated_tool_specific",
        "status": "deprecated",
        "replacement": "beta git-stage",
        "description": "Legacy Git staging gate.",
    },
    ("sandbox", "prepare"): {
        "script": "tools/sandbox_boundary/prepare_sandbox_run.py",
        "fixed_args": [],
        "mode": "sandbox_write",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "mission run",
        "description": "Legacy sandbox preparation.",
    },
    ("artifact", "write"): {
        "script": "tools/artifact_writer/write_sandbox_artifact.py",
        "fixed_args": [],
        "mode": "sandbox_write",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "mission run",
        "description": "Legacy artifact writer.",
    },
    ("apply", "preview"): {
        "script": "tools/apply_plan/apply_sandbox_plan.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": None,
        "description": "Legacy apply preview.",
    },
    ("apply", "confirm"): {
        "script": "tools/apply_plan/apply_sandbox_plan.py",
        "fixed_args": ["--confirm-apply"],
        "mode": "repository_write",
        "network": "blocked",
        "approval_token": "delegated_tool_specific",
        "status": "deprecated",
        "replacement": None,
        "description": "Legacy controlled apply.",
    },
    ("config", "validate"): {
        "script": "tools/config_validator/validate_konoha_config.py",
        "fixed_args": [],
        "mode": "read_only",
        "network": "blocked",
        "approval_token": None,
        "status": "deprecated",
        "replacement": "doctor",
        "description": "Legacy config validator.",
    },
}

ALL_COMMANDS: Dict[CommandKey, Dict[str, Any]] = {
    **COMMAND_REGISTRY,
    **LEGACY_COMMANDS,
}


def command_label(key: CommandKey) -> str:
    return " ".join(key)
